async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = false
caption_extension = ".txt"
clip_skip = 2
dynamo_backend = "inductor"
enable_bucket = true
epoch = 1
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = false
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
learning_rate = 5e-6
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 4
persistent_workers = true
max_grad_norm = 1.0
max_timestep = 600
max_token_length = 75
max_train_steps = 800
min_bucket_reso = 256
min_snr_gamma = 1
mixed_precision = "bf16"
network_alpha = 48
network_args = [
  "dropout=0.05", 
  "rank_dropout=0.05",
  "module_dropout=0.0",
  "algo=lora"
]
network_dim = 96
network_module = "networks.lora"
no_half_vae = false
noise_offset_type = "Original"
noise_offset = 0.15
optimizer_args = ["weight_decay=0.01"]
optimizer_type = "adamw"
output_dir = "/app/outputs"
output_name = "last"
pin_memory = true
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
resolution = "896,896"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 30
save_model_as = "safetensors"
save_precision = "bf16"
seed = 42
scale_weight_norms = 1
text_encoder_lr = 1.5e-6
train_batch_size = 8
train_data_dir = ""
training_comment = ""
unet_lr = 4e-6
xformers = true
tokenizer_path = "stabilityai/stable-diffusion-xl-base-1.0"
